name: TheOther165.com
favicon: null
layout_spectrum: 0.50304
typography_spectrum: 0.48674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d4c91'
    - '#ed1b24'
    - '#9aa9cc'
    - '#f04f3d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
