name: TheOther165.com
favicon: null
layout_spectrum: 0.014276430243626237
typography_spectrum: 0.7272052781190723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d4c91'
    - '#ed1b24'
    - '#9aa9cc'
    - '#f04f3d'
  brandStrength: 0.1911380544770509
  lightness: 0.7503487332724035
  saturation: 0.9374137145932764
  rhythmicContrast: 0.47375740855932236
purpose: []
